package org.mmocore.gameserver.network.lineage.components;

import org.mmocore.gameserver.network.lineage.serverpackets.*;
import org.mmocore.gameserver.network.lineage.serverpackets.GoodsInventory.ExGoodsInventoryChangedNotify;
import org.mmocore.gameserver.network.lineage.serverpackets.GoodsInventory.ExGoodsInventoryInfo;
import org.mmocore.gameserver.network.lineage.serverpackets.GoodsInventory.ExGoodsInventoryResult;
import org.mmocore.gameserver.network.lineage.serverpackets.ItemModification.AttributeItem.ExAttributeEnchantResult;
import org.mmocore.gameserver.network.lineage.serverpackets.ItemModification.AttributeItem.ExBaseAttributeCancelResult;
import org.mmocore.gameserver.network.lineage.serverpackets.ItemModification.AttributeItem.ExChooseInventoryAttributeItem;
import org.mmocore.gameserver.network.lineage.serverpackets.ItemModification.AttributeItem.ExShowBaseAttributeCancelWindow;
import org.mmocore.gameserver.network.lineage.serverpackets.ItemModification.EnchantScroll.ExPutEnchantSupportItemResult;
import org.mmocore.gameserver.network.lineage.serverpackets.ItemModification.EnchantScroll.ExPutEnchantTargetItemResult;
import org.mmocore.gameserver.network.lineage.serverpackets.ItemModification.RefineItem.*;
import org.mmocore.gameserver.network.lineage.serverpackets.Moving.*;
import org.mmocore.gameserver.network.lineage.serverpackets.PremiumShop.*;

/**
 * @author: Camelion, KilRoy
 * @date: 01.08.13/0:47
 * int __cdecl sub_20479FD0()
 */
public enum SecondServerPacketOpcode {
    _0x00, // Dummy
    EX_REGEN_MAX(ExRegenMax.class),
    EX_EVENT_MATCH_USER_INFO(ExEventMatchUserInfo.class),
    EX_COLOSSEUM_FENCE_INFO(ExColosseumFenceInfo.class),
    EX_EVENT_MATCH_SPELLED_INFO(ExEventMatchSpelledInfo.class),
    EX_EVENT_MATCH_FIRECRACKER(ExEventMatchFirecracker.class),
    EX_EVENT_MATCH_TEAM_UNLOCKED(ExEventMatchTeamUnlocked.class),
    EX_EVENT_MATCH_GM_TEST(ExEventMatchGMTest.class),
    EX_PARTY_ROOM_MEMBER(ExPartyRoomMember.class),
    EX_CLOSE_PARTY_ROOM(ExClosePartyRoom.class),
    EX_MANAGE_PARTY_ROOM_MEMBER(ExManagePartyRoomMember.class),
    EX_EVENT_MATCH_LOCK(ExEventMatchLockResult.class),
    EX_AUTO_SOUL_SHOT(ExAutoSoulShot.class),
    EX_EVENT_MATCH_LIST(ExEventMatchList.class),
    EX_EVENT_MATCH_OBSERVER(ExEventMatchObserver.class),
    EX_EVENT_MATCH_MESSAGE(ExEventMatchMessage.class),

    EX_EVENT_MATCH_SCORE(ExEventMatchScore.class),
    EX_SERVER_PRIMITIVE(ExServerPrimitive.class),
    EX_OPEN_MPCC(ExMPCCOpen.class),
    EX_CLOSE_MPCC(ExMPCCClose.class),
    EX_SHOW_CASTLE_INFO(ExShowCastleInfo.class),
    EX_SHOW_FORTRESS_INFO(ExShowFortressInfo.class),
    EX_SHOW_AGIT_INFO(ExShowAgitInfo.class),
    EX_SHOW_FORTRESS_SIEGE_INFO(ExShowFortressSiegeInfo.class),
    EX_PARTY_PET_WINDOW_ADD(ExPartyPetWindowAdd.class),
    EX_PARTY_PET_WINDOW_UPDATE(ExPartyPetWindowUpdate.class),
    EX_ASK_JOIN_MPCC(ExAskJoinMPCC.class),
    EX_PLEDGE_EMBLEM(ExPledgeCrestLarge.class),
    EX_EVENT_MATCH_TEAM_INFO(ExEventMatchTeamInfo.class),
    EX_EVENT_MATCH_CREATE(ExEventMatchCreate.class),
    EX_FINISH_START(ExFishingStart.class),
    EX_FINISH_END(ExFishingEnd.class),

    EX_SHOW_QUEST_INFO(ExShowQuestInfo.class),
    EX_SHOW_QUEST_MARK(ExShowQuestMark.class),
    EX_SEND_MANOR_LIST(ExSendManorList.class),
    EX_SHOW_SEED_INFO(ExShowSeedInfo.class),
    EX_SHOW_CROP_INFO(ExShowCropInfo.class),
    EX_SHOW_MANOR_DEFAULT_INFO(ExShowManorDefaultInfo.class),
    EX_SHOW_SEED_SETTING(ExShowSeedSetting.class),
    EX_FISHING_START_COMBAT(ExFishingStartCombat.class),
    EX_FISHING_HP_REGEN(ExFishingHpRegen.class),
    EX_ENCHANT_SKILL_LIST(ExEnchantSkillList.class),
    EX_ENCHANT_SKILL_INFO(ExEnchantSkillInfo.class),
    EX_SHOW_CROP_SETTING(ExShowCropSetting.class),
    EX_SHOW_SELL_CROP_LIST(ExShowSellCropList.class),
    EX_OLYMPIAD_MATCH_END(ExOlympiadMatchEnd.class),
    EX_MAIL_ARRIVED(ExMailArrived.class),
    EX_STORAGE_MAX_COUNT(ExStorageMaxCount.class),

    EX_EVENT_MATCH_MANAGE(ExEventMatchManage.class),
    EX_MULTI_PARTY_COMMAND_CHANEL_INFO(ExMultiPartyCommandChannelInfo.class),
    EX_PC_CAFE_POINT_INFO(ExPCCafePointInfo.class),
    EX_SET_COMPASS_ZONE_CODE(ExSetCompassZoneCode.class),
    EX_GET_BOSS_RECORD(ExGetBossRecord.class),
    EX_ASK_JOIN_PARTY_ROOM(ExAskJoinPartyRoom.class),
    EX_LIST_PARTY_MATCHING_WAITING_ROOM(ExListPartyMatchingWaitingRoom.class),
    EX_SET_MPCC_ROUTING(ExSetMpccRouting.class),
    EX_SHOW_ADVENTURE_GUIDE_BOOK(ExShowAdventurerGuideBook.class),
    EX_SHOW_SCREEN_MESSAGE(ExShowScreenMessage.class),
    PLEDGE_SKILL_LIST(PledgeSkillList.class),
    PLEDGE_SKILL_LIST_ADD(PledgeSkillListAdd.class),
    PLEDGE_POWER_GRADE_LIST(PledgePowerGradeList.class),
    PLEDGE_RECEIVE_POWER_INFO(PledgeReceivePowerInfo.class),
    PLEDGE_RECEIVE_MEMBER_INFO(PledgeReceiveMemberInfo.class),
    PLEDGE_RECEIVE_WAR_LIST(PledgeReceiveWarList.class),

    PLEDGE_RECEIVE_SUB_PLEDGE_CREATED(PledgeReceiveSubPledgeCreated.class),
    EX_RED_SKY(ExRedSky.class),
    PLEDGE_RECEIVE_UPDATE_POWER(PledgeReceiveUpdatePower.class),
    FLY_SELF_DESTINATION(FlySelfDestination.class),
    SHOW_PC_CAFE_COUPON_SHOW_UI(ShowPCCafeCouponShowUI.class),
    EX_SEARCH_ORC(ExSearchOrc.class),
    EX_CURSED_WEAPON_LIST(ExCursedWeaponList.class),
    EX_CURSED_WEAPON_LOCATION(ExCursedWeaponLocation.class),
    EX_RESTART_CLIENT(ExRestartClient.class),
    EX_REQUEST_HACK_SHIELD(ExRequestHackShield.class),
    EX_USE_SHARED_GROUP_ITEM(ExUseSharedGroupItem.class),
    EX_MPCC_SHOW_PARTY_MEMBER_INFO(ExMPCCShowPartyMemberInfo.class),
    EX_DUEL_ASK_START(ExDuelAskStart.class),
    EX_DUEL_READY(ExDuelReady.class),
    EX_DUEL_START(ExDuelStart.class),
    EX_DUEL_END(ExDuelEnd.class),

    EX_DUEL_UPDATE_USER_INFO(ExDuelUpdateUserInfo.class),
    EX_SHOW_VARIATION_MAKE_WINDOW(ExShowVariationMakeWindow.class),
    EX_SHOW_VARIATION_CANCEL_WINDOW(ExShowVariationCancelWindow.class),
    EX_PUT_ITEM_RESULT_FOR_VARIATION_MAKE(ExPutItemResultForVariationMake.class),
    EX_PUT_INTENSIVE_RESULT_FOR_VARIATION_MAKE(ExPutIntensiveResultForVariationMake.class),
    EX_PUT_COMMUSSION_RESULT_FOR_VARIATION_MAKE(ExPutCommissionResultForVariationMake.class),
    EX_VARIATION_RESULT(ExVariationResult.class),
    EX_PUT_ITEM_RESULT_FOR_VARIATION_CANCEL(ExPutItemResultForVariationCancel.class),
    EX_VARIATION_CANCEL_RESULT(ExVariationCancelResult.class),
    EX_DUEL_ENEMY_RELATION(ExDuelEnemyRelation.class),
    EX_PLAY_ANIMATION(ExPlayAnimation.class),
    EX_MPCC_PARTY_INFO_UPDATE(ExMPCCPartyInfoUpdate.class),
    EX_PLAY_SCENE(ExPlayScene.class),
    EX_SPAWN_EMMITTRE(ExSpawnEmitter.class),
    EX_ENCHANT_SKILL_INFO_DETAIL(ExEnchantSkillInfoDetail.class),
    EX_BASIC_ACTION_LIST(ExBasicActionList.class),

    EX_AIR_SHIP_INFO(ExAirShipInfo.class),
    EX_ATTRIBUTE_ENCHANT_RESULT(ExAttributeEnchantResult.class),
    EX_CHOOSE_INVENTORY_ATTRIBUTE_ITEM(ExChooseInventoryAttributeItem.class),
    EX_GET_ON_AIR_SHIP(ExGetOnAirShip.class),
    EX_GET_OFF_AIR_SHIP(ExGetOffAirShip.class),
    EX_MOVE_TO_LOCATION_AIR_SHIP(ExMoveToLocationAirShip.class),
    EX_STOP_MOVE_AIR_SHIP(ExStopMoveAirShip.class),
    EX_SHOW_TRACE(ExShowTrace.class),
    EX_ITEM_AUCTION_INFO(ExItemAuctionInfo.class),
    EX_NEED_TO_CHANGE_NAME(ExNeedToChangeName.class),
    EX_PARTY_PET_WINDOW_DELETE(ExPartyPetWindowDelete.class),
    EX_TUTORIAL_LIST(ExTutorialList.class),
    EX_RP_ITEM_LINK(ExRpItemLink.class),
    EX_MOVE_TO_LOCATION_IN_AIR_SHIP(ExMoveToLocationInAirShip.class),
    EX_STOP_MOVE_IN_AIR_SHIP(ExStopMoveInAirShip.class),
    EX_VALIDATE_LOCATION_IN_AIR_SHIP(ExValidateLocationInAirShip.class),

    EX_UI_SETTING(ExUISetting.class),
    EX_MOVE_TO_TARGET_IN_AIR_SHIP(ExMoveToTargetInAirShip.class),
    EX_ATTACK_IN_AIR_SHIP(ExAttackInAirShip.class),
    EX_MAGIC_SKILL_USE_IN_AIR_SHIP(ExMagicSkillUseInAirShip.class),
    EX_SHOW_BASE_ATTRIBUTE_CANCEL_WINDOW(ExShowBaseAttributeCancelWindow.class),
    EX_BASE_ATTRIBUTE_CANCEL_RESULT(ExBaseAttributeCancelResult.class),
    EX_SUB_PLEDGE_SKILL_ADD(ExSubPledgeSkillAdd.class),
    EX_RESPONSE_FREE_SERVER(ExResponseFreeServer.class),
    EX_SHOW_PROCURE_CROP_DETAIL(ExShowProcureCropDetail.class),
    EX_HERO_LIST(ExHeroList.class),
    EX_OLYMPIAD_USER_INFO(ExOlympiadUserInfo.class),
    EX_OLYMPIAD_SPELLED_INFO(ExOlympiadSpelledInfo.class),
    EX_OLYMPIAD_MODE(ExOlympiadMode.class),
    EX_SHOW_FORTRESS_MAP_INFO(ExShowFortressMapInfo.class),
    EX_PVP_MATCH_RECORD(ExPVPMatchRecord.class),
    EX_PVP_MATCH_USER_DIE(ExPVPMatchUserDie.class),

    EX_PRIVATE_STORE_WHOLE_MSG(ExPrivateStoreWholeMsg.class),
    EX_PUT_ENCHANT_TARGET_ITEM_RESULT(ExPutEnchantTargetItemResult.class),
    EX_PUT_ENCHANT_SUPPORT_ITEM_RESULT(ExPutEnchantSupportItemResult.class),
    EX_CHANGE_NICKNAME_N_COLOR(ExChangeNicknameNColor.class),
    EX_GET_BOOK_MARK_INFO(ExGetBookMarkInfo.class),
    EX_NOTIFY_PREMIUM_ITEM(ExNotifyPremiumItem.class),
    EX_GET_PREMIUM_ITEM(ExGetPremiumItemList.class),
    EX_PERIODIC_ITEM_LIST(ExPeriodicItemList.class),
    EX_JUMP_TO_LOCATION(ExJumpToLocation.class),
    EX_PVP_MATCH_CC_RECORD(ExPVPMatchCCRecord.class),
    EX_PVP_MATCH_CC_MY_RECORD(ExPVPMatchCCMyRecord.class),
    EX_PVP_MATCH_CC_RETIRE(ExPVPMatchCCRetire.class),
    EX_SHOW_TERRITORY(ExShowTerritory.class),
    EX_NPC_QUEST_HTML_MESSAGE(ExNpcQuestHtmlMessage.class),
    EX_SEND_UI_EVENT(ExSendUIEvent.class),
    EX_NOTIFY_BIRTH_DAY(ExNotifyBirthDay.class),

    EX_SHOW_DOMINION_REGISTRY(ExShowDominionRegistry.class),
    EX_REPLY_REGISTER_DOMINION(ExReplyRegisterDominion.class),
    EX_REPLY_DOMINION_INFO(ExReplyDominionInfo.class),
    EX_SHOW_OWNTHING_POS(ExShowOwnthingPos.class),
    EX_CLEFT_LIST(ExCleftList.class),
    EX_CLEFT_STATE(ExCleftState.class),
    EX_DOMINION_CHANNEL_SET(ExDominionChannelSet.class),
    EX_BLOCK_UP_SET_LIST(ExBlockUpSetList.class),
    EX_BLOCK_UP_SET_STATE(ExBlockUpSetState.class),
    EX_START_SCENE_PLAYER(ExStartScenePlayer.class),
    EX_AIR_SHIP_TELEPORT_LIST(ExAirShipTeleportList.class),
    EX_MPCC_ROOM_INFO(ExMpccRoomInfo.class),
    EX_LIST_MPCC_WAITING(ExListMpccWaiting.class),
    EX_DISSMISS_MPCC_ROOM(ExDissmissMpccRoom.class),
    EX_MANAGE_MPCC_ROOM_MEMBER(ExManageMpccRoomMember.class),
    EX_MPCC_ROOM_MEMBER(ExMpccRoomMember.class),

    EX_VITALITY_POINT_INFO(ExVitalityPointInfo.class),
    EX_SHOW_SEED_MAP_INFO(ExShowSeedMapInfo.class),
    EX_MPCC_PARTY_MASTER_LIST(ExMpccPartymasterList.class),
    EX_DOMINION_WAR_START(ExDominionWarStart.class),
    EX_DOMINION_WAR_END(ExDominionWarEnd.class),
    EX_SHOW_LINES(ExShowLines.class),
    EX_PARTY_MEMBER_RENAMED(ExPartyMemberRenamed.class),
    EX_ENCHANT_SKILL_RESULT(ExEnchantSkillResult.class),
    EX_REFUND_LIST(ExRefundList.class),
    EX_NOTICE_POST_ARRIVED(ExNoticePostArrived.class),
    EX_SHOW_RECEIVED_POST_LIST(ExShowReceivedPostList.class),
    EX_REPLY_RECEIVED_POST(ExReplyReceivedPost.class),
    EX_SHOW_SENT_POST_LIST(ExShowSentPostList.class),
    EX_REPLY_SENT_POST(ExReplySentPost.class),
    EX_RESPONSE_SHOW_STEP_ONE(ExResponseShowStepOne.class),
    EX_RESPONSE_SHOW_STEP_TWO(ExResponseShowStepTwo.class),

    EX_RESPONSE_SHOW_CONTENTS(ExResponseShowContents.class),
    EX_SHOW_PETITION_HTML(ExShowPetitionHtml.class),
    EX_REPLY_POST_ITEN_LIST(ExReplyPostItemList.class),
    EX_CHANGE_POST_STATE(ExChangePostState.class),
    EX_REPLY_WRITE_POST(ExReplyWritePost.class),
    EX_INITIALIZE_SEED(ExInitializeSeed.class),
    EX_RAID_RESERVE_RESULT(ExRaidReserveResult.class),
    _0xB7, // ExBuySellList TODO[K]
    EX_CLOSE_RAID_SOCKET(ExCloseRaidSocket.class),
    EX_PRIVATE_MARKET_LIST(ExPrivateMarketList.class),
    EX_RAID_CHARACTER_SELECTED(ExRaidCharacterSelected.class),
    EX_ASK_COUPLE_ACTION(ExAskCoupleAction.class),
    EX_BR_BROADCAST_EVENT_STATE(ExBR_BroadcastEventState.class),
    EX_BR_LOAD_EVENT_TOP_RANKERS(ExBR_LoadEventTopRankers.class),
    EX_CHANGE_NPC_STATE(ExChangeNpcState.class),
    EX_ASK_MODIFY_PARTY_LOOTING(ExAskModifyPartyLooting.class),

    EX_SET_PARTY_LOOTING(ExSetPartyLooting.class),
    EX_ROTATION(ExRotation.class),
    EX_CHANGE_CLIENT_EFFECT_INFO(ExChangeClientEffectInfo.class),
    EX_MEMBERSHIP_INFO(ExMembershipInfo.class),
    EX_REPLY_HAND_OVER_PARTY_MASTER(ExReplyHandOverPartyMaster.class),
    EX_QUEST_NPC_LOG_LIST(ExQuestNpcLogList.class),
    EX_QUEST_ITEM_LIST(ExQuestItemList.class),
    EX_GM_VIEW_QUEST_ITEM_LIST(ExGMViewQuestItemList.class),
    EX_RESTART_RESPONSE(ExResartResponse.class),
    EX_VOTE_SYSTEM_INFO(ExVoteSystemInfo.class),
    EX_SHUTTLE_INFO(ExShuttuleInfo.class),
    EX_SHUTTLE_GET_ON(ExSuttleGetOn.class),
    EX_SHUTTLE_GET_OFF(ExSuttleGetOff.class),
    EX_SHUTTLE_MOVE(ExSuttleMove.class),
    EX_MTL_IN_SHUTTLE(ExMTLInSuttle.class),
    EX_STOP_MOVE_IN_SHUTTLE(ExStopMoveInShuttle.class),

    EX_VALIDATE_LOCATION_IN_SHUTTLE(ExValidateLocationInShuttle.class),
    EX_AGIT_AUCTION_CMD(ExAgitAuctionCmd.class),
    EX_CONFIRM_ADDING_POST_FRIEND(ExConfirmAddingPostFriend.class),
    EX_RECEIVE_SHOW_POST_FRIEND(ExReceiveShowPostFriend.class),
    _0xD4,//EX_RECEIVE_OLYMPIAD(ExReceiveOlympiad.class), TODO[K]
    EX_BR_GAME_POINT(ExBR_GamePoint.class),
    EX_BR_PRODUCT_LIST(ExBR_ProductList.class),
    EX_BR_PRODUCT_INFO(ExBR_ProductInfo.class),
    EX_BR_BUY_PRODUCT(ExBR_BuyProduct.class),
    EX_BR_PREMIUM_STATE(ExBR_PremiumState.class),
    EX_BR_EXTRA_USER_INFO(ExBR_ExtraUserInfo.class),
    EX_BR_BUFF_EVENT_STATE(ExBR_BuffEventState.class),
    EX_BR_RECENT_PRODUCT_LIST(ExBR_RecentProductListPacket.class),
    EX_BR_MINIGAMELOADSCORES(ExBR_MiniGameLoadScores.class),
    EX_BR_AGATHION_ENERGY_INFO(ExBR_AgathionEnergyInfo.class),
    EX_NAVIT_ADVENT_POINT_INFO(ExNavitAdventPointInfo.class),

    EX_NAVIT_ADVENT_EFFECT(ExNavitAdventEffect.class),
    EX_NAVIT_ADVENT_TIME_CHANGE(ExNavitAdventTimeChange.class),
    EX_GOODS_INVENTORY_CHANGE_NOTIFY(ExGoodsInventoryChangedNotify.class),
    EX_GOODS_INVENTORY_INFO(ExGoodsInventoryInfo.class),
    EX_GOODS_INVENTORY_RESULT(ExGoodsInventoryResult.class),
    EX_2ND_PASSWORD_CHECK(Ex2ndPasswordCheck.class),
    EX_2ND_PASSWORD_VERIFY(Ex2ndPasswordVerify.class),
    EX_2ND_PASSWORD_ACK(Ex2ndPasswordAck.class),
    EX_SAY_2_FAIL(ExSay2Fail.class),
    _0xE9,
    _0xEA,
    _0xEB,
    _0xEC,
    _0xED,
    _0xEE,
    _0xEF,

    _0xF0,
    _0xF1,
    _0xF2,
    _0xF3,
    _0xF4,
    _0xF5,
    _0xF6,
    _0xF7,
    _0xF8,
    _0xF9,
    _0xFA,
    _0xFB,
    _0xFC,
    _0xFD,
    _0xFE;

    final Class<? extends GameServerPacket> clazz;

    SecondServerPacketOpcode() {
        this(null);
    }

    SecondServerPacketOpcode(Class<? extends GameServerPacket> clazz) {
        this.clazz = clazz;
    }
}
